from setuptools import setup, find_packages

setup(
    name='algofacto',
    version='0.0.1',
    packages=find_packages(),
    url='',
    license='',
    author='jofan1256',
    author_email='jonathan.fan@yale.edu',
    description='Creating algotrading models',
    # install_requires=['pandas_datareader',
    #                   'tqdm',
    #                   'pandas',
    #                   'numpy==1.23.1',
    #                   'yfinance',
    #                   'matplotlib',
    #                   'scikit-learn',
    #                   'statsmodels',
    #                   'scipy',
    #                   'xgboost',
    #                   'PyWavelets',
    #                   'pyarrow',
    #                   'cloudpickle',
    #                   'prettytable',
    #                   'ipython',
    #                   'Jupyter',
    #                   'pandarallel',
    #                   'shap'],
)
